# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ereignisse.ui'
#
# Created: Tue Mar 16 16:26:37 2010
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Ereignisse(object):
    def setupUi(self, Ereignisse):
        Ereignisse.setObjectName("Ereignisse")
        Ereignisse.resize(431,492)
        self.dockWidgetContents = QtGui.QWidget(Ereignisse)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0,0,426,463))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lcdNumber = QtGui.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout.addWidget(self.lcdNumber_2)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout.addWidget(self.lcdNumber_3)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout.addWidget(self.lcdNumber_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lcdNumber_5 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.verticalLayout_2.addWidget(self.lcdNumber_5)
        self.lcdNumber_6 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.verticalLayout_2.addWidget(self.lcdNumber_6)
        self.lcdNumber_7 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.verticalLayout_2.addWidget(self.lcdNumber_7)
        self.lcdNumber_8 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.verticalLayout_2.addWidget(self.lcdNumber_8)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lcdNumber_9 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.verticalLayout_3.addWidget(self.lcdNumber_9)
        self.lcdNumber_10 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.verticalLayout_3.addWidget(self.lcdNumber_10)
        self.lcdNumber_11 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.verticalLayout_3.addWidget(self.lcdNumber_11)
        self.lcdNumber_12 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.verticalLayout_3.addWidget(self.lcdNumber_12)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.lcdNumber_13 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.verticalLayout_4.addWidget(self.lcdNumber_13)
        self.lcdNumber_14 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.verticalLayout_4.addWidget(self.lcdNumber_14)
        self.lcdNumber_15 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.verticalLayout_4.addWidget(self.lcdNumber_15)
        self.lcdNumber_16 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.verticalLayout_4.addWidget(self.lcdNumber_16)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        spacerItem = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.qwtPlot = QwtPlot(self.widget)
        self.qwtPlot.setProperty("propertiesDocument",QtCore.QVariant(QtGui.QApplication.translate("Ereignisse", "Zeitlicher Verlauf der Raten", None, QtGui.QApplication.UnicodeUTF8)))
        self.qwtPlot.setObjectName("qwtPlot")
        self.verticalLayout_7.addWidget(self.qwtPlot)
        Ereignisse.setWidget(self.dockWidgetContents)

        self.retranslateUi(Ereignisse)
        QtCore.QObject.connect(self.pushButton,QtCore.SIGNAL("clicked()"),self.qwtPlot.clear)
        QtCore.QObject.connect(self.pushButton_2,QtCore.SIGNAL("clicked()"),self.qwtPlot.replot)
        QtCore.QMetaObject.connectSlotsByName(Ereignisse)

    def retranslateUi(self, Ereignisse):
        Ereignisse.setWindowTitle(QtGui.QApplication.translate("Ereignisse", "Ereignisse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Ereignisse", "Kanal", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Ereignisse", "Kanal 0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Ereignisse", "Kanal 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Ereignisse", "Kanal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Ereignisse", "Kanal 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Ereignisse", "Ereignisse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Ereignisse", "Letze ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Ereignisse", "Rate in Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Ereignisse", "Fehler", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Ereignisse", "Leeren", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Ereignisse", "Aktualisieren", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4.Qwt5 import QwtPlot
