# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Optionen.ui'
#
# Created: Tue Mar 16 16:28:01 2010
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(458,341)
        self.allgemein = QtGui.QWidget()
        self.allgemein.setObjectName("allgemein")
        self.widget = QtGui.QWidget(self.allgemein)
        self.widget.setGeometry(QtCore.QRect(0,0,451,311))
        self.widget.setObjectName("widget")
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_30 = QtGui.QLabel(self.widget)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_31.addWidget(self.label_30)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_31 = QtGui.QLabel(self.widget)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_24.addWidget(self.label_31)
        self.comboBox_4 = QtGui.QComboBox(self.widget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_24.addWidget(self.comboBox_4)
        self.verticalLayout_31.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_32 = QtGui.QLabel(self.widget)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_25.addWidget(self.label_32)
        self.lineEdit_3 = QtGui.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_25.addWidget(self.lineEdit_3)
        self.verticalLayout_31.addLayout(self.horizontalLayout_25)
        self.verticalLayout_33.addLayout(self.verticalLayout_31)
        self.line_9 = QtGui.QFrame(self.widget)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_33.addWidget(self.line_9)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_33 = QtGui.QLabel(self.widget)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_26.addWidget(self.label_33)
        self.comboBox_5 = QtGui.QComboBox(self.widget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_26.addWidget(self.comboBox_5)
        self.verticalLayout_33.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_35 = QtGui.QLabel(self.widget)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_30.addWidget(self.label_35)
        self.comboBox_6 = QtGui.QComboBox(self.widget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_30.addWidget(self.comboBox_6)
        self.verticalLayout_33.addLayout(self.horizontalLayout_30)
        self.line_7 = QtGui.QFrame(self.widget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_33.addWidget(self.line_7)
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.checkBox_10 = QtGui.QCheckBox(self.widget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_28.addWidget(self.checkBox_10)
        self.pushButton_21 = QtGui.QPushButton(self.widget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_28.addWidget(self.pushButton_21)
        self.verticalLayout_32.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_34 = QtGui.QLabel(self.widget)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_27.addWidget(self.label_34)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_27.addWidget(self.lineEdit_4)
        self.verticalLayout_32.addLayout(self.horizontalLayout_27)
        self.verticalLayout_33.addLayout(self.verticalLayout_32)
        self.line_8 = QtGui.QFrame(self.widget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_33.addWidget(self.line_8)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.pushButton_22 = QtGui.QPushButton(self.widget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_29.addWidget(self.pushButton_22)
        self.pushButton_23 = QtGui.QPushButton(self.widget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_29.addWidget(self.pushButton_23)
        self.pushButton_24 = QtGui.QPushButton(self.widget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_29.addWidget(self.pushButton_24)
        self.pushButton_26 = QtGui.QPushButton(self.widget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_29.addWidget(self.pushButton_26)
        self.pushButton_25 = QtGui.QPushButton(self.widget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_29.addWidget(self.pushButton_25)
        self.verticalLayout_33.addLayout(self.horizontalLayout_29)
        TabWidget.addTab(self.allgemein,"")
        self.bedingungen = QtGui.QWidget()
        self.bedingungen.setObjectName("bedingungen")
        self.widget1 = QtGui.QWidget(self.bedingungen)
        self.widget1.setGeometry(QtCore.QRect(0,0,451,321))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_23 = QtGui.QLabel(self.widget1)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_29 = QtGui.QLabel(self.widget1)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_20.addWidget(self.label_29)
        self.horizontalLayout_18.addLayout(self.verticalLayout_20)
        self.spinBox_5 = QtGui.QSpinBox(self.widget1)
        self.spinBox_5.setMaximum(1512)
        self.spinBox_5.setSingleStep(24)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_18.addWidget(self.spinBox_5)
        self.label_26 = QtGui.QLabel(self.widget1)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_18.addWidget(self.label_26)
        self.verticalLayout_23.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_24 = QtGui.QLabel(self.widget1)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_21.addWidget(self.label_24)
        self.horizontalLayout_19.addLayout(self.verticalLayout_21)
        self.spinBox_6 = QtGui.QSpinBox(self.widget1)
        self.spinBox_6.setMaximum(9128)
        self.spinBox_6.setSingleStep(24)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_19.addWidget(self.spinBox_6)
        self.label_27 = QtGui.QLabel(self.widget1)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.verticalLayout_23.addLayout(self.horizontalLayout_19)
        self.verticalLayout_25.addLayout(self.verticalLayout_23)
        self.line_3 = QtGui.QFrame(self.widget1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_25.addWidget(self.line_3)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_25 = QtGui.QLabel(self.widget1)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_22.addWidget(self.label_25)
        self.horizontalLayout_20.addLayout(self.verticalLayout_22)
        self.spinBox_7 = QtGui.QSpinBox(self.widget1)
        self.spinBox_7.setMinimum(24)
        self.spinBox_7.setMaximum(3048)
        self.spinBox_7.setSingleStep(24)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_20.addWidget(self.spinBox_7)
        self.label_28 = QtGui.QLabel(self.widget1)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        self.verticalLayout_25.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21.addLayout(self.verticalLayout_25)
        self.line_4 = QtGui.QFrame(self.widget1)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_21.addWidget(self.line_4)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.pushButton_13 = QtGui.QPushButton(self.widget1)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_24.addWidget(self.pushButton_13)
        self.pushButton_14 = QtGui.QPushButton(self.widget1)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_24.addWidget(self.pushButton_14)
        self.pushButton_15 = QtGui.QPushButton(self.widget1)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_24.addWidget(self.pushButton_15)
        self.pushButton_16 = QtGui.QPushButton(self.widget1)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_24.addWidget(self.pushButton_16)
        self.horizontalLayout_21.addLayout(self.verticalLayout_24)
        self.verticalLayout_29.addLayout(self.horizontalLayout_21)
        self.line_5 = QtGui.QFrame(self.widget1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_29.addWidget(self.line_5)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.groupBox = QtGui.QGroupBox(self.widget1)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0,20,91,111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_30.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_30.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_30.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_30.addWidget(self.radioButton_4)
        self.verticalLayout_26.addWidget(self.groupBox)
        self.horizontalLayout_22.addLayout(self.verticalLayout_26)
        self.groupBox_2 = QtGui.QGroupBox(self.widget1)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget2 = QtGui.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(10,20,90,111))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.checkBox_9 = QtGui.QCheckBox(self.widget2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_27.addWidget(self.checkBox_9)
        self.radioButton_5 = QtGui.QRadioButton(self.widget2)
        self.radioButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_27.addWidget(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.widget2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_27.addWidget(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.widget2)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_27.addWidget(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.widget2)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_27.addWidget(self.radioButton_8)
        self.horizontalLayout_22.addWidget(self.groupBox_2)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_22)
        self.line_6 = QtGui.QFrame(self.widget1)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_23.addWidget(self.line_6)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.pushButton_17 = QtGui.QPushButton(self.widget1)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_28.addWidget(self.pushButton_17)
        self.pushButton_18 = QtGui.QPushButton(self.widget1)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_28.addWidget(self.pushButton_18)
        self.pushButton_19 = QtGui.QPushButton(self.widget1)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_28.addWidget(self.pushButton_19)
        self.pushButton_20 = QtGui.QPushButton(self.widget1)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_28.addWidget(self.pushButton_20)
        self.horizontalLayout_23.addLayout(self.verticalLayout_28)
        self.verticalLayout_29.addLayout(self.horizontalLayout_23)
        TabWidget.addTab(self.bedingungen,"")
        self.speichern = QtGui.QWidget()
        self.speichern.setObjectName("speichern")
        self.widget3 = QtGui.QWidget(self.speichern)
        self.widget3.setGeometry(QtCore.QRect(0,0,451,313))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_3 = QtGui.QCheckBox(self.widget3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_12.addWidget(self.checkBox_3)
        self.comboBox_3 = QtGui.QComboBox(self.widget3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_12.addWidget(self.comboBox_3)
        self.verticalLayout_19.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_22 = QtGui.QLabel(self.widget3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_16.addWidget(self.label_22)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_16.addWidget(self.lineEdit_2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.line = QtGui.QFrame(self.widget3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_15.addWidget(self.line)
        self.checkBox_4 = QtGui.QCheckBox(self.widget3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_15.addWidget(self.checkBox_4)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtGui.QLabel(self.widget3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.widget3)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_13.addWidget(self.dateTimeEdit)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_20 = QtGui.QLabel(self.widget3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_14.addWidget(self.label_20)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.widget3)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout_14.addWidget(self.dateTimeEdit_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.verticalLayout_19.addLayout(self.verticalLayout_15)
        self.line_2 = QtGui.QFrame(self.widget3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_19.addWidget(self.line_2)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_21 = QtGui.QLabel(self.widget3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_18.addWidget(self.label_21)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.checkBox_5 = QtGui.QCheckBox(self.widget3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_17.addWidget(self.checkBox_5)
        self.checkBox_6 = QtGui.QCheckBox(self.widget3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_17.addWidget(self.checkBox_6)
        self.horizontalLayout_15.addLayout(self.verticalLayout_17)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.checkBox_7 = QtGui.QCheckBox(self.widget3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_16.addWidget(self.checkBox_7)
        self.checkBox_8 = QtGui.QCheckBox(self.widget3)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_16.addWidget(self.checkBox_8)
        self.horizontalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_18.addLayout(self.horizontalLayout_15)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_10 = QtGui.QPushButton(self.widget3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_17.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(self.widget3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_17.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(self.widget3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_17.addWidget(self.pushButton_12)
        self.verticalLayout_19.addLayout(self.horizontalLayout_17)
        TabWidget.addTab(self.speichern,"")
        self.speicherort = QtGui.QWidget()
        self.speicherort.setObjectName("speicherort")
        self.widget4 = QtGui.QWidget(self.speicherort)
        self.widget4.setGeometry(QtCore.QRect(0,0,451,311))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.comboBox = QtGui.QComboBox(self.widget4)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_13.addWidget(self.comboBox)
        self.treeView = QtGui.QTreeView(self.widget4)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_13.addWidget(self.treeView)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtGui.QLabel(self.widget4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.lineEdit = QtGui.QLineEdit(self.widget4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_18 = QtGui.QLabel(self.widget4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.comboBox_2 = QtGui.QComboBox(self.widget4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_9.addWidget(self.comboBox_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_7 = QtGui.QPushButton(self.widget4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_14.addWidget(self.pushButton_7)
        spacerItem = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem)
        self.pushButton_8 = QtGui.QPushButton(self.widget4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_14.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.widget4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_14.addWidget(self.pushButton_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        TabWidget.addTab(self.speicherort,"")
        self.schwellspannung = QtGui.QWidget()
        self.schwellspannung.setObjectName("schwellspannung")
        self.widget5 = QtGui.QWidget(self.schwellspannung)
        self.widget5.setGeometry(QtCore.QRect(0,0,453,311))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtGui.QLabel(self.widget5)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.checkBox_11 = QtGui.QCheckBox(self.widget5)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_5.addWidget(self.checkBox_11)
        self.label_9 = QtGui.QLabel(self.widget5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtGui.QSpinBox(self.widget5)
        self.spinBox.setMaximum(4079)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_5 = QtGui.QLabel(self.widget5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtGui.QLabel(self.widget5)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.lcdNumber = QtGui.QLCDNumber(self.widget5)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.line_10 = QtGui.QFrame(self.widget5)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_5.addWidget(self.line_10)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtGui.QLabel(self.widget5)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.checkBox_12 = QtGui.QCheckBox(self.widget5)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_6.addWidget(self.checkBox_12)
        self.label_14 = QtGui.QLabel(self.widget5)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_2 = QtGui.QSpinBox(self.widget5)
        self.spinBox_2.setMaximum(4079)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.label_6 = QtGui.QLabel(self.widget5)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_11 = QtGui.QLabel(self.widget5)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.widget5)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_2.addWidget(self.lcdNumber_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.line_11 = QtGui.QFrame(self.widget5)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_5.addWidget(self.line_11)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtGui.QLabel(self.widget5)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.checkBox_13 = QtGui.QCheckBox(self.widget5)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_7.addWidget(self.checkBox_13)
        self.label_15 = QtGui.QLabel(self.widget5)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBox_3 = QtGui.QSpinBox(self.widget5)
        self.spinBox_3.setMaximum(4079)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.label_7 = QtGui.QLabel(self.widget5)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtGui.QLabel(self.widget5)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.widget5)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout_3.addWidget(self.lcdNumber_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.line_12 = QtGui.QFrame(self.widget5)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_5.addWidget(self.line_12)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtGui.QLabel(self.widget5)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.checkBox_14 = QtGui.QCheckBox(self.widget5)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_8.addWidget(self.checkBox_14)
        self.label_16 = QtGui.QLabel(self.widget5)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spinBox_4 = QtGui.QSpinBox(self.widget5)
        self.spinBox_4.setMaximum(4079)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.label_8 = QtGui.QLabel(self.widget5)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtGui.QLabel(self.widget5)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.widget5)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout_4.addWidget(self.lcdNumber_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox = QtGui.QCheckBox(self.widget5)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_9.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.widget5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_9.addWidget(self.checkBox_2)
        spacerItem2 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton = QtGui.QPushButton(self.widget5)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_11.addWidget(self.pushButton)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtGui.QPushButton(self.widget5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.widget5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_4 = QtGui.QPushButton(self.widget5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widget5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.widget5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        TabWidget.addTab(self.schwellspannung,"")
        self.Zusatzoptionen = QtGui.QWidget()
        self.Zusatzoptionen.setObjectName("Zusatzoptionen")
        self.widget6 = QtGui.QWidget(self.Zusatzoptionen)
        self.widget6.setGeometry(QtCore.QRect(0,0,451,318))
        self.widget6.setObjectName("widget6")
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.widget6)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.verticalLayout_34 = QtGui.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_40 = QtGui.QLabel(self.widget6)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_34.addWidget(self.label_40)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_36 = QtGui.QLabel(self.widget6)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_34.addWidget(self.label_36)
        self.spinBox_8 = QtGui.QSpinBox(self.widget6)
        self.spinBox_8.setMaximum(3)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_34.addWidget(self.spinBox_8)
        self.verticalLayout_34.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_37 = QtGui.QLabel(self.widget6)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_33.addWidget(self.label_37)
        self.spinBox_9 = QtGui.QSpinBox(self.widget6)
        self.spinBox_9.setMaximum(3)
        self.spinBox_9.setProperty("value",QtCore.QVariant(1))
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_33.addWidget(self.spinBox_9)
        self.verticalLayout_34.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_38 = QtGui.QLabel(self.widget6)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_32.addWidget(self.label_38)
        self.spinBox_10 = QtGui.QSpinBox(self.widget6)
        self.spinBox_10.setMaximum(3)
        self.spinBox_10.setProperty("value",QtCore.QVariant(2))
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_32.addWidget(self.spinBox_10)
        self.verticalLayout_34.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_39 = QtGui.QLabel(self.widget6)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_31.addWidget(self.label_39)
        self.spinBox_11 = QtGui.QSpinBox(self.widget6)
        self.spinBox_11.setMaximum(3)
        self.spinBox_11.setProperty("value",QtCore.QVariant(3))
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_31.addWidget(self.spinBox_11)
        self.verticalLayout_34.addLayout(self.horizontalLayout_31)
        self.line_13 = QtGui.QFrame(self.widget6)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_34.addWidget(self.line_13)
        self.label_41 = QtGui.QLabel(self.widget6)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_34.addWidget(self.label_41)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_42 = QtGui.QLabel(self.widget6)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_35.addWidget(self.label_42)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.widget6)
        self.doubleSpinBox.setMaximum(10000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_35.addWidget(self.doubleSpinBox)
        self.verticalLayout_34.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_43 = QtGui.QLabel(self.widget6)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_36.addWidget(self.label_43)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.widget6)
        self.doubleSpinBox_2.setMaximum(100000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_36.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_34.addLayout(self.horizontalLayout_36)
        self.line_14 = QtGui.QFrame(self.widget6)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_34.addWidget(self.line_14)
        self.horizontalLayout_38.addLayout(self.verticalLayout_34)
        self.graphicsView = QtGui.QGraphicsView(self.widget6)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_38.addWidget(self.graphicsView)
        self.verticalLayout_35.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.pushButton_30 = QtGui.QPushButton(self.widget6)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_37.addWidget(self.pushButton_30)
        self.pushButton_28 = QtGui.QPushButton(self.widget6)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_37.addWidget(self.pushButton_28)
        self.pushButton_27 = QtGui.QPushButton(self.widget6)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_37.addWidget(self.pushButton_27)
        self.pushButton_29 = QtGui.QPushButton(self.widget6)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_37.addWidget(self.pushButton_29)
        self.verticalLayout_35.addLayout(self.horizontalLayout_37)
        TabWidget.addTab(self.Zusatzoptionen,"")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(QtGui.QApplication.translate("TabWidget", "Optionen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("TabWidget", "Konfiguration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("TabWidget", "Laden", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("TabWidget", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("TabWidget", "Port der DAQ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("TabWidget", "Baudrate", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("TabWidget", "Wetterdaten online Abfragen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("TabWidget", "Überprüfen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("TabWidget", "Webadresse", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("TabWidget", "Zurücksetzen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("TabWidget", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("TabWidget", "Abbrechen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_26.setText(QtGui.QApplication.translate("TabWidget", "Anwenden", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_25.setText(QtGui.QApplication.translate("TabWidget", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.allgemein), QtGui.QApplication.translate("TabWidget", "Allgemein", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("TabWidget", "Schrankenbreite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("TabWidget", "unterer Einzugsbereich", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("TabWidget", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("TabWidget", "oberer Einzugsbereich ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("TabWidget", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("TabWidget", "TMC - Verzögerung       ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("TabWidget", "ns", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("TabWidget", "Air-Shower", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("TabWidget", "Myonendurchfluss", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("TabWidget", "Myonenzerfall", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("TabWidget", "Standart", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TabWidget", "Koinzidenz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("TabWidget", "aus", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("TabWidget", "2 Platten", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("TabWidget", "3 Platten", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("TabWidget", "alle Platten", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("TabWidget", "Veto", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("TabWidget", "Einschalten", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("TabWidget", "Kanal 0", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("TabWidget", "Kanal 1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("TabWidget", "Kanal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("TabWidget", "Kanal 3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("TabWidget", "Zurücksetzen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("TabWidget", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("TabWidget", "Abbrechen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("TabWidget", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.bedingungen), QtGui.QApplication.translate("TabWidget", "Bedingungen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("TabWidget", "Autospeichern aller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("TabWidget", "Ort der Autospeicherdatei", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("TabWidget", "Timer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("TabWidget", "Start der Messung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("TabWidget", "Ende der Messung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("TabWidget", "Speicher", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("TabWidget", "alle Ereignisse", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("TabWidget", "Ereignisse nach Bedingungen", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("TabWidget", "Myonenzerfälle", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("TabWidget", "Myonendurchgänge", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("TabWidget", "Abbrechen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("TabWidget", "Anwenden", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("TabWidget", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.speichern), QtGui.QApplication.translate("TabWidget", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("TabWidget", "Dateiname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("TabWidget", "Dateityp", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("TabWidget", "Neuer Ordner", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("TabWidget", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("TabWidget", "Abbrechen", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.speicherort), QtGui.QApplication.translate("TabWidget", "Speicherort", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TabWidget", "Kanal 0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("TabWidget", "Aktiv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TabWidget", "Schwellspannung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TabWidget", "mV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TabWidget", "Rate in Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TabWidget", "Kanal 1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("TabWidget", "Aktiv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("TabWidget", "Schwellspannung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TabWidget", "mV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TabWidget", "Rate in Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TabWidget", "Kanal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("TabWidget", "Aktiv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("TabWidget", "Schwellspannung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TabWidget", "mV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("TabWidget", "Rate in Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TabWidget", "Kanal 3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("TabWidget", "Aktiv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("TabWidget", "Schwellspannung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TabWidget", "mV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("TabWidget", "Rate in Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("TabWidget", "Autoeinstellung", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("TabWidget", "Warnhinweis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("TabWidget", "Kalibierungsassistent", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("TabWidget", "Zurücksetzten", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("TabWidget", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("TabWidget", "Abbrechen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("TabWidget", "Anwenden", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("TabWidget", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.schwellspannung), QtGui.QApplication.translate("TabWidget", "Schwellspannung", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("TabWidget", "Anpassungen an Messaufbau", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("TabWidget", "Kanal 0 liegt auf Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("TabWidget", "Kanal 1 liegt auf Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("TabWidget", "Kanal 2 liegt auf Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("TabWidget", "Kanal 3 liegt auf Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("TabWidget", "Abstände zwischen den Platten", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("TabWidget", "s in mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("TabWidget", "h in mm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_30.setText(QtGui.QApplication.translate("TabWidget", "Zurücksetzen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_28.setText(QtGui.QApplication.translate("TabWidget", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_27.setText(QtGui.QApplication.translate("TabWidget", "Abbrechen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_29.setText(QtGui.QApplication.translate("TabWidget", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.Zusatzoptionen), QtGui.QApplication.translate("TabWidget", "Zusatzoptionen", None, QtGui.QApplication.UnicodeUTF8))

