# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Koinzidenzmessung.ui'
#
# Created: Tue Mar 16 16:27:04 2010
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Koinzidenzmessung(object):
    def setupUi(self, Koinzidenzmessung):
        Koinzidenzmessung.setObjectName("Koinzidenzmessung")
        Koinzidenzmessung.resize(256,520)
        self.dockWidgetContents = QtGui.QWidget(Koinzidenzmessung)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0,0,255,495))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.lcdNumber_20 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.verticalLayout_4.addWidget(self.lcdNumber_20)
        self.lcdNumber_21 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.verticalLayout_4.addWidget(self.lcdNumber_21)
        self.lcdNumber_22 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.verticalLayout_4.addWidget(self.lcdNumber_22)
        self.lcdNumber_23 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.verticalLayout_4.addWidget(self.lcdNumber_23)
        self.lcdNumber_24 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_24.setObjectName("lcdNumber_24")
        self.verticalLayout_4.addWidget(self.lcdNumber_24)
        self.lcdNumber_25 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_25.setObjectName("lcdNumber_25")
        self.verticalLayout_4.addWidget(self.lcdNumber_25)
        self.lcdNumber_26 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_26.setObjectName("lcdNumber_26")
        self.verticalLayout_4.addWidget(self.lcdNumber_26)
        self.lcdNumber_27 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_27.setObjectName("lcdNumber_27")
        self.verticalLayout_4.addWidget(self.lcdNumber_27)
        self.lcdNumber_28 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_28.setObjectName("lcdNumber_28")
        self.verticalLayout_4.addWidget(self.lcdNumber_28)
        self.lcdNumber_29 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_29.setObjectName("lcdNumber_29")
        self.verticalLayout_4.addWidget(self.lcdNumber_29)
        self.lcdNumber_30 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_30.setObjectName("lcdNumber_30")
        self.verticalLayout_4.addWidget(self.lcdNumber_30)
        self.lcdNumber_31 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_31.setObjectName("lcdNumber_31")
        self.verticalLayout_4.addWidget(self.lcdNumber_31)
        self.lcdNumber_32 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_32.setObjectName("lcdNumber_32")
        self.verticalLayout_4.addWidget(self.lcdNumber_32)
        self.lcdNumber_33 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_33.setObjectName("lcdNumber_33")
        self.verticalLayout_4.addWidget(self.lcdNumber_33)
        self.lcdNumber_34 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_34.setObjectName("lcdNumber_34")
        self.verticalLayout_4.addWidget(self.lcdNumber_34)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lcdNumber = QtGui.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_2.addWidget(self.lcdNumber)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_2.addWidget(self.lcdNumber_2)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout_2.addWidget(self.lcdNumber_3)
        self.lcdNumber_4 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout_2.addWidget(self.lcdNumber_4)
        self.lcdNumber_9 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.verticalLayout_2.addWidget(self.lcdNumber_9)
        self.lcdNumber_10 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.verticalLayout_2.addWidget(self.lcdNumber_10)
        self.lcdNumber_11 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.verticalLayout_2.addWidget(self.lcdNumber_11)
        self.lcdNumber_12 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.verticalLayout_2.addWidget(self.lcdNumber_12)
        self.lcdNumber_13 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.verticalLayout_2.addWidget(self.lcdNumber_13)
        self.lcdNumber_14 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.verticalLayout_2.addWidget(self.lcdNumber_14)
        self.lcdNumber_15 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.verticalLayout_2.addWidget(self.lcdNumber_15)
        self.lcdNumber_16 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.verticalLayout_2.addWidget(self.lcdNumber_16)
        self.lcdNumber_17 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.verticalLayout_2.addWidget(self.lcdNumber_17)
        self.lcdNumber_18 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.verticalLayout_2.addWidget(self.lcdNumber_18)
        self.lcdNumber_19 = QtGui.QLCDNumber(self.widget)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.verticalLayout_2.addWidget(self.lcdNumber_19)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        Koinzidenzmessung.setWidget(self.dockWidgetContents)

        self.retranslateUi(Koinzidenzmessung)
        QtCore.QObject.connect(self.pushButton,QtCore.SIGNAL("clicked()"),self.lcdNumber_34.setDecMode)
        QtCore.QObject.connect(self.pushButton_2,QtCore.SIGNAL("clicked()"),self.lcdNumber_34.setDecMode)
        QtCore.QMetaObject.connectSlotsByName(Koinzidenzmessung)

    def retranslateUi(self, Koinzidenzmessung):
        Koinzidenzmessung.setWindowTitle(QtGui.QApplication.translate("Koinzidenzmessung", "Koinzidenzmessung", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0 + 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0 + 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0 + 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 1 + 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 1 + 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 2 + 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0 + 1 + 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0 + 1 + 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0 + 2 + 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 1 + 2 + 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kanal 0 + 1 + 2 + 3 ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Ereignisse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Rate in Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Leeren", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Koinzidenzmessung", "Kopieren", None, QtGui.QApplication.UnicodeUTF8))

